daemon off;
events { worker_connections 1024; }

http {
    upstream edge_servers {
        server 192.168.1.16:8080; # Edge Laptop 1
        server 192.168.1.17:8080; # Edge Laptop 2
    }

    server {
        listen 8080;

        location /live/ {
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            proxy_pass http://edge_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
        }
    }
}