events {
    worker_connections 1024;
}

# The HTTP Proxy: Grabs chunks from the receiver and gives them to the Frontend
http {
    server {
        # for frontend video player
        listen 8080;
        
        # When frontend requests a stream URL ending in /live/...
        location /live/ {
            #  HOTLINK PROTECTION (security guard)

            # Only allow requests from our frontend (and direct browser hits for testing)
            valid_referers none blocked localhost 127.0.0.1;
            
            if ($invalid_referer) {
                return 403;
            }

            # Reach across the Docker network to grab chunks from your Origin server
            proxy_pass http://nginx-origin:80/hls/;
            
            # CDN Caching (Caches the chunk for 10 seconds to save Origin bandwidth)
            add_header Cache-Control "public, max-age=10";
            
            # CORS Security (Crucial: React player will be instantly blocked by the browser if this is missing)
            add_header Access-Control-Allow-Origin *;
        }
    }
}
