events {
    worker_connections 1024;
}

http {
    #  THE POOL - Horizontal Scaling 
    upstream edge_servers {
        server nginx-edge-1:8080;
        server nginx-edge-2:8080;
    }

    server {
        listen 8080;

        location /live/ {
            # Forward the request to one of the servers in the pool 
            proxy_pass http://edge_servers;

            # Ensure we pass the correct headers so the edge knows the original request
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
