events {
    worker_connections 1024;
}

# The RTMP block: Receives the live feed from OBS on port 1935
rtmp {
    server {
        listen 1935;
        application live {
            live on;
            
            # Webhook 1: Asks backend API if the user's Stream Key is valid
            on_publish http://backend-api:3000/api/webhooks/stream-start;
            
            # Slice the live video into playable HLS chunks for live viewing
            hls on;
            hls_path /tmp/hls;
            hls_fragment 3s;

            # Save a raw .flv copy of the broadcast to the hard drive
            record all;
            record_path /tmp/recordings;
            record_unique on;

            # Webhook 2: Stream End (Trigger Vasu's Worker Node)
            on_record_done http://backend-api:3000/api/webhooks/stream-end;
        }
    }
}

# The HTTP block: Internal server so nginx-edge can grab chunks & backend can grab stats
http {
    server {
        listen 80;
        
        location /hls {
            # Looks inside the temporary folder where the RTMP block saved the chunks
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;
        }
        
        # Exposes real-time viewer counts for Prankit's backend to fetch
        location /stats {
            rtmp_stat all;
            # Allows internal Docker traffic to read the stats without CORS blocks
            allow all; 
        }
    }
}