daemon off;
events { worker_connections 1024; }

http {
    server {
        listen 8080;
        
        location /live/ {
            proxy_pass http://192.168.1.14:80/hls/;
            
            add_header Cache-Control "public, max-age=10";
            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Origin, Range, Accept, Content-Type, Authorization" always;
            add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;
            add_header Vary "Origin" always;
        }
    }
}