services:
  backend-api:
    image: node:20-alpine
    container_name: hexanodes_backend_api
    working_dir: /app
    volumes:
      - ./backend-api:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      PORT: 3000
      CORS_ORIGIN: "*"
      MONGO_URI: mongodb://[PC1_IP]:27017,[PC2_IP]:27017,[PC3_IP]:27017/VideoDS?replicaSet=rs0
      DB_NAME: VideoDS
      ACCESS_TOKEN_SECRET: dev_access_secret_change_me
      ACCESS_TOKEN_EXPIRY: 1d
      REFRESH_TOKEN_SECRET: dev_refresh_secret_change_me
      REFRESH_TOKEN_EXPIRY: 10d
      RABBITMQ_URL: amqp://[PC1_IP]:5672
      MINIO_ENDPOINT: [PC1_IP]
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password123
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx-origin:
    image: tiangolo/nginx-rtmp
    container_name: hexanodes_origin
    ports:
      - "1935:1935" 
      - "80:80" 
    volumes:
      - ./nginx-origin/nginx.conf:/etc/nginx/nginx.conf
      - recordings_data:/tmp/recordings
    command: /bin/sh -c "chmod 777 /tmp/recordings && nginx -g 'daemon off;'"
    restart: unless-stopped

volumes:
  recordings_data: